### ISSUE TITLE
[1.20.1] Friends and foes crash on launch

### ISSUE THREAD

**Issue by MrKashew** [Faboslav/friends-and-foes#117]
### Minecraft version information

1.20.1

### Mod loader information

Forge

### Mod loader version information

47.0.3

### Mod version information

1.9.0

### Reproduction Steps

launch

### Crash Report and latest.log

[18Jun2023 22:40:52.551] [pool-3-thread-1/DEBUG] [mixin/]: Mixing LightningEntityMixin from friendsandfoes-common.mixins.json into net.minecraft.world.entity.LightningBolt
[18Jun2023 22:40:52.552] [pool-3-thread-1/DEBUG] [mixin/]: Renaming synthetic method lambda$friendsandfoes_decreaseCustomOxidationStates$0(Lnet/minecraft/world/level/Level;Lnet/minecraft/core/BlockPos;Lnet/minecraft/world/level/block/state/BlockState;)V to mdaa0bf3$lambda$friendsandfoes_decreaseCustomOxidationStates$0$2 in friendsandfoes-common.mixins.json:LightningEntityMixin
[18Jun2023 22:40:52.567] [pool-3-thread-1/FATAL] [mixin/]: Mixin apply failed friendsandfoes-common.mixins.json:LightningEntityMixin -> net.minecraft.world.entity.LightningBolt: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException InjectionPoint(Shift)[@At("INVOKE")] on net/minecraft/world/entity/LightningBolt::friendsandfoes_decreaseCustomOxidationStates with priority 1000 cannot inject into net/minecraft/world/entity/LightningBolt::m_147153_(Lnet/minecraft/world/level/Level;Lnet/minecraft/core/BlockPos;)Ljava/util/Optional; merged by net.Davidak.NatureArise.Mixin.LightningBoltMixin with priority 1000 [PREINJECT Applicator Phase -> friendsandfoes-common.mixins.json:LightningEntityMixin -> Prepare Injections ->  -> handler$cnn000$friendsandfoes_decreaseCustomOxidationStates(Lnet/minecraft/world/level/Level;Lnet/minecraft/core/BlockPos;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Ljava/util/Iterator;Lnet/minecraft/core/BlockPos;Lnet/minecraft/world/level/block/state/BlockState;)V -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: InjectionPoint(Shift)[@At("INVOKE")] on net/minecraft/world/entity/LightningBolt::friendsandfoes_decreaseCustomOxidationStates with priority 1000 cannot inject into net/minecraft/world/entity/LightningBolt::m_147153_(Lnet/minecraft/world/level/Level;Lnet/minecraft/core/BlockPos;)Ljava/util/Optional; merged by net.Davidak.NatureArise.Mixin.LightningBoltMixin with priority 1000 [PREINJECT Applicator Phase -> friendsandfoes-common.mixins.json:LightningEntityMixin -> Prepare Injections ->  -> handler$cnn000$friendsandfoes_decreaseCustomOxidationStates(Lnet/minecraft/world/level/Level;Lnet/minecraft/core/BlockPos;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Ljava/util/Iterator;Lnet/minecraft/core/BlockPos;Lnet/minecraft/world/level/block/state/BlockState;)V -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1319) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1042) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.9.jar:10.0.9+10.0.9+main.dcd20f30]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.world.level.block.Blocks.<clinit>(Blocks.java:1090) ~[client-1.20.1-20230612.114412-srg.jar%23528!/:?]
	at net.minecraft.world.level.block.FireBlock.m_53484_(FireBlock.java:301) ~[client-1.20.1-20230612.114412-srg.jar%23528!/:?]
	at net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:46) ~[client-1.20.1-20230612.114412-srg.jar%23528!/:?]
	at net.minecraft.client.main.Main.lambda$main$0(Main.java:151) ~[client-1.20.1-20230612.114412-srg.jar%23528!/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Faboslav** [comment]
I tested this with the forge of `46.0.1`, forge is currently in its beta(no stable release) so it can happen, will need to take a look at that.

**Comment by Faboslav** [comment]
This should be resolved with newest version of the mod, can you please try and let me know?

**Comment by MrKashew** [comment]
I can test it tonight 👀

**Comment by MrKashew** [comment]
not sure if its in the current release - launch crash is still happening on the new release
```
[22/06/2023 20:02:08 PM] [pool-4-thread-1/FATAL] Mixin apply failed friendsandfoes-common.mixins.json:LightningEntityMixin -> net.minecraft.world.entity.LightningBolt: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException InjectionPoint(Shift)[@At("INVOKE")] on net/minecraft/world/entity/LightningBolt::friendsandfoes_decreaseCustomOxidationStates with priority 1000 cannot inject into net/minecraft/world/entity/LightningBolt::m_147153_(Lnet/minecraft/world/level/Level;Lnet/minecraft/core/BlockPos;)Ljava/util/Optional; merged by net.Davidak.NatureArise.Mixin.LightningBoltMixin with priority 1000 [PREINJECT Applicator Phase -> friendsandfoes-common.mixins.json:LightningEntityMixin -> Prepare Injections ->  -> handler$cee000$friendsandfoes_decreaseCustomOxidationStates(Lnet/minecraft/world/level/Level;Lnet/minecraft/core/BlockPos;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Ljava/util/Iterator;Lnet/minecraft/core/BlockPos;Lnet/minecraft/world/level/block/state/BlockState;)V -> Prepare]
[22/06/2023 20:02:08 PM] Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[22/06/2023 20:02:08 PM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:32)
[22/06/2023 20:02:08 PM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
[22/06/2023 20:02:08 PM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
[22/06/2023 20:02:08 PM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
[22/06/2023 20:02:08 PM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
[22/06/2023 20:02:08 PM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
[22/06/2023 20:02:08 PM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
[22/06/2023 20:02:08 PM] 	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
[22/06/2023 20:02:08 PM] Caused by: java.lang.reflect.InvocationTargetException
[22/06/2023 20:02:08 PM] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22/06/2023 20:02:08 PM] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[22/06/2023 20:02:08 PM] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22/06/2023 20:02:08 PM] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[22/06/2023 20:02:08 PM] 	at MC-BOOTSTRAP/fmlloader@1.20.1-47.0.14/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
[22/06/2023 20:02:08 PM] 	at MC-BOOTSTRAP/fmlloader@1.20.1-47.0.14/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99)
[22/06/2023 20:02:08 PM] 	at MC-BOOTSTRAP/fmlloader@1.20.1-47.0.14/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25)
[22/06/2023 20:02:08 PM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
[22/06/2023 20:02:08 PM] 	... 7 more
[22/06/2023 20:02:08 PM] Caused by: java.lang.RuntimeException: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[22/06/2023 20:02:08 PM] 	at MC-BOOTSTRAP/fmlloader@1.20.1-47.0.14/net.minecraftforge.fml.loading.BackgroundWaiter.runAndTick(BackgroundWaiter.java:32)
[22/06/2023 20:02:08 PM] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.main.Main.main(Main.java:151)
[22/06/2023 20:02:08 PM] 	... 15 more
[22/06/2023 20:02:08 PM] Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[22/06/2023 20:02:08 PM] 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
[22/06/2023 20:02:08 PM] 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
[22/06/2023 20:02:08 PM] 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
[22/06/2023 20:02:08 PM] 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
[22/06/2023 20:02:08 PM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156)
[22/06/2023 20:02:08 PM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
[22/06/2023 20:02:08 PM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
[22/06/2023 20:02:08 PM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
[22/06/2023 20:02:08 PM] 	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113)
[22/06/2023 20:02:08 PM] 	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219)
[22/06/2023 20:02:08 PM] 	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229)
[22/06/2023 20:02:08 PM] 	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219)
[22/06/2023 20:02:08 PM] 	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135)
[22/06/2023 20:02:08 PM] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[22/06/2023 20:02:08 PM] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.Blocks.<clinit>(Blocks.java:1090)
[22/06/2023 20:02:08 PM] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.FireBlock.m_53484_(FireBlock.java:301)
[22/06/2023 20:02:08 PM] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:46)
[22/06/2023 20:02:08 PM] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.main.Main.lambda$main$0(Main.java:151)
[22/06/2023 20:02:08 PM] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[22/06/2023 20:02:08 PM] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[22/06/2023 20:02:08 PM] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[22/06/2023 20:02:08 PM] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[22/06/2023 20:02:08 PM] 	at java.base/java.lang.Thread.run(Thread.java:833)
[22/06/2023 20:02:08 PM] Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [friendsandfoes-common.mixins.json:LightningEntityMixin] from phase [DEFAULT] in config [friendsandfoes-common.mixins.json] FAILED during APPLY
[22/06/2023 20:02:08 PM] 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:636)
[22/06/2023 20:02:08 PM] 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:588)
[22/06/2023 20:02:08 PM] 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
[22/06/2023 20:02:08 PM] 	... 22 more
[22/06/2023 20:02:08 PM] Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: InjectionPoint(Shift)[@At("INVOKE")] on net/minecraft/world/entity/LightningBolt::friendsandfoes_decreaseCustomOxidationStates with priority 1000 cannot inject into net/minecraft/world/entity/LightningBolt::m_147153_(Lnet/minecraft/world/level/Level;Lnet/minecraft/core/BlockPos;)Ljava/util/Optional; merged by net.Davidak.NatureArise.Mixin.LightningBoltMixin with priority 1000 [PREINJECT Applicator Phase -> friendsandfoes-common.mixins.json:LightningEntityMixin -> Prepare Injections ->  -> handler$cee000$friendsandfoes_decreaseCustomOxidationStates(Lnet/minecraft/world/level/Level;Lnet/minecraft/core/BlockPos;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Ljava/util/Iterator;Lnet/minecraft/core/BlockPos;Lnet/minecraft/world/level/block/state/BlockState;)V -> Prepare]
[22/06/2023 20:02:08 PM] 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305)
[22/06/2023 20:02:08 PM] 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
[22/06/2023 20:02:08 PM] 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421)
[22/06/2023 20:02:08 PM] 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1319)
[22/06/2023 20:02:08 PM] 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1042)
[22/06/2023 20:02:08 PM] 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)
[22/06/2023 20:02:08 PM] 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
[22/06/2023 20:02:08 PM] 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
[22/06/2023 20:02:08 PM] 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
[22/06/2023 20:02:08 PM] 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[22/06/2023 20:02:08 PM] 	... 22 more
```

**Comment by Faboslav** [comment]
I am not sure why this is happening, i tested latest forge with latest release, which is currently 1.9.1 and it was fine :/.

**Comment by ooliver1** [comment]
Same issue with me on forge 47.1.0, what is forge 1.9.1?

**Comment by Faboslav** [comment]
1.9.1 is friends&foes mod version. I will try to reproduce this once more, but if there is not a deterministic way to reproduce, then i sadly dont know what to do with this for the time being

**Comment by lgowen22** [comment]
I'm getting crashes upon launch as well, but I'm using quilt. Only mods active are QSL and Friends and Foes.

**Comment by Faboslav** [comment]
Great then! I will continue to keep the quilt version of the mod up to date. Hopefully someday it will work on it's own, and you wont need the fabric version.
