### ISSUE TITLE
[1.19.2] lightning rod crash between this mod and Caverns and Chasms

### ISSUE THREAD

**Issue by B-Wither** [Faboslav/friends-and-foes#273]
### Minecraft version information

1.19.2

### Mod loader information

Forge

### Mod loader version information

43.3.5

### Mod version information

3.0.3

### Reproduction Steps

It suddenly happend, not sure what caused that but seeing crash report it seems to be conflict between those two mods.

### Crash Report and latest.log

[crash-2024-10-10_21.33.42-client.txt](https://github.com/user-attachments/files/17328161/crash-2024-10-10_21.33.42-client.txt)
[latest.log](https://github.com/user-attachments/files/17328162/latest.log)

**Comment by digi2303** [comment]
Try use [Neruina](https://modrinth.com/mod/neruina)

**Comment by B-Wither** [comment]
Thanks!

**Comment by digi2303** [comment]
And if you want the delete the same items that two mod add just write a comment

**Comment by Faboslav** [comment]
This will be officially fixed with the next release :).

**Comment by B-Wither** [comment]
[crash-2024-07-23_14.20.47-client.txt](https://github.com/user-attachments/files/17349355/crash-2024-07-23_14.20.47-client.txt)
Seems still happened, will keep open until fixed in the next update.

**Comment by Faboslav** [comment]
Fix for this error should be out with the 3.0.4 release.
